"""update Table

Revision ID: f86f699f45be
Revises: 2b1c151992db
Create Date: 2023-10-05 22:34:32.940959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86f699f45be'
down_revision: Union[str, None] = '2b1c151992db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.add_column('courses', sa.Column('department', sa.String(), nullable=True))
    op.add_column('grades', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'grade')
    op.drop_column('courses', 'department')
    op.drop_table('student_courses')
    # ### end Alembic commands ###
